# Generated by Django 2.2.13 on 2020-09-27 18:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=20)),
                ('thumbnail_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(200, 200), (400, 400)]), size=None)),
                ('original_link', models.BooleanField()),
                ('expiring_link', models.BooleanField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
