# Generated by Django 2.2.13 on 2020-09-27 21:17

from django.db import migrations


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("users.Plan")
    Plan.objects.create(
        name="Basic",
        thumbnail_sizes=[200],
        original_link=False,
        expiring_link=False,
    )
    Plan.objects.create(
        name="Premium",
        thumbnail_sizes=[200, 400],
        original_link=True,
        expiring_link=False,
    )
    Plan.objects.create(
        name="Enterprise",
        thumbnail_sizes=[200, 400],
        original_link=True,
        expiring_link=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_plans),
    ]
